In [ ]:
# Data Cleaning and Preprocessing

## Objective
To clean and preprocess the Iris dataset provided by Codveda Technology.

In [3]:
pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.1-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.5.2/libexec/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.5.2/libexec/lib/python3.14/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.5.2/libexec/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp314-cp314-macosx_11_0_arm64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 152.4 kB/s  0:00:58157.6 kB/s eta 0:00:02
Downloading numpy-2.4.1-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.5/5.2 MB 114.3 kB/s eta 0:00:41
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (524 kB/5.2 MB, attempt 1)
Resuming download numpy-2.4.1-cp314-cp314-macosx_14_0_arm64.whl (524 kB/5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 2.6/5.2 MB 28.8 kB/s eta 0:01:30m
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (2.6 MB/5.2 MB, attempt 2)
Resuming download numpy-2.4.1-cp314-cp314-macosx_14_0_arm64.whl (2.6 MB/5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 3.9/5.2 MB 95.7 kB/s eta 0:00:14m
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (3.9 MB/5.2 MB, attempt 3)
Resuming download numpy-2.4.1-cp314-cp314-macosx_14_0_arm64.whl (3.9 MB/5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 106.0 kB/s  0:00:122.9 kB/s eta 0:00:02
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]━━━━━━━━━━━ 2/3 [pandas]
Successfully installed numpy-2.4.1 pandas-2.3.3 pytz-2025.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("raw_dataset.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

No missing values were found in the dataset.

In [6]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [3]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /opt/homebrew/Cellar/jupyterlab/4.5.2/libexec/lib/python3.14/site-packages (from scikit-learn) (2.4.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.0-cp314-cp314-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 162.2 kB/s  0:00:45160.2 kB/s eta 0:00:02
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.0-cp314-cp314-macosx_14_0_arm64.whl (20.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.1/20.1 MB 171.2 kB/s  0:01:41 eta 0:00:02[36m0:00:05
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn]0m 3/4 [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.0 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv("raw_dataset.csv")
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

df = pd.read_csv("raw_dataset.csv")

# Encode categorical column
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

# Scale numerical features
scaler = StandardScaler()
numeric_cols = df.select_dtypes(include=np.number).columns
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

df.head()

   sepal_length  sepal_width  petal_length  petal_width   species
0     -0.900681     1.032057     -1.341272    -1.312977 -1.224745
1     -1.143017    -0.124958     -1.341272    -1.312977 -1.224745
2     -1.385353     0.337848     -1.398138    -1.312977 -1.224745
3     -1.506521     0.106445     -1.284407    -1.312977 -1.224745
4     -1.021849     1.263460     -1.341272    -1.312977 -1.224745

The target column 'species' contained categorical values, which were converted into numerical form using Label Encoding.
Feature scaling was applied only to numerical columns using StandardScaler.

In [9]:
df.to_csv("cleaned_dataset.csv", index=False)